### PR TITLE
fix(connector): [elavon] fixed elavon currency issue and error parsing

### LINKED ISSUE #1043: [Connector]-[Elavon]  Authorize Returns `Failed to deserialize connector response` (500)
### Summary

Two bugs in the Elavon connector implementation cause all Authorize calls to fail with a 500 error on standard single-currency terminals. Both issues are in `crates/integrations/connector-integration/src/connectors/elavon/transformers.rs`.

---

#### Description

`CardPaymentRequest` includes `ssl_transaction_currency: Currency` as a **required field** that is serialized and sent to Elavon on every Authorize request. According to [Elavon's API reference](https://developer.elavon.com/products/hosted-payment-page/v1/api-reference#tag/Process-Transaction-Online/operation/process), this field is only valid for terminals that have **Multi-Currency Conversion (MCC)** or **Dynamic Currency Conversion (DCC)** explicitly enabled. Standard single-currency terminals reject any request containing this field with error `5087`.

> From [Elavon docs](https://developer.elavon.com/products/hosted-payment-page/v1/api-reference#tag/Process-Transaction-Online/operation/process):
> _"Multi-Currency Conversion (object) or Dynamic Currency Conversion (object) — Used to sell products and services in a variety of currencies. Verify terminal is setup with this option by sending `ssl_transaction_type = terminalsetup` with your credentials."_

#### Current behaviour

Every Authorize request sent by the connector includes `<ssl_transaction_currency>USD</ssl_transaction_currency>` (or whichever currency), causing Elavon to immediately reject it:

```xml
<txn>
  <errorCode>5087</errorCode>
  <errorName>Transaction currency not allowed for this terminal</errorName>
  <errorMessage>Transaction currency is not allowed for this terminal. Your terminal must be setup with Multi currency</errorMessage>
</txn>
```

#### Reproduce

```bash
# Fails — ssl_transaction_currency sent on a standard terminal
curl -s -X POST 'https://api.demo.convergepay.com/VirtualMerchantDemo/processxml.do' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'xmldata=<txn>
  <ssl_transaction_type>ccsale</ssl_transaction_type>
  <ssl_merchant_id>YOUR_MERCHANT_ID</ssl_merchant_id>
  <ssl_user_id>YOUR_USER_ID</ssl_user_id>
  <ssl_pin>YOUR_PIN</ssl_pin>
  <ssl_amount>10.00</ssl_amount>
  <ssl_card_number>4000000000000002</ssl_card_number>
  <ssl_exp_date>1230</ssl_exp_date>
  <ssl_cvv2cvc2>123</ssl_cvv2cvc2>
  <ssl_transaction_currency>USD</ssl_transaction_currency>
</txn>'
```

**Response:**
```xml
<txn>
  <errorCode>5087</errorCode>
  <errorName>Transaction currency not allowed for this terminal</errorName>
  <errorMessage>Transaction currency is not allowed for this terminal. Your terminal must be setup with Multi currency</errorMessage>
</txn>
```

```bash
# Succeeds — without ssl_transaction_currency
curl -s -X POST 'https://api.demo.convergepay.com/VirtualMerchantDemo/processxml.do' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  --data-urlencode 'xmldata=<txn>
  <ssl_transaction_type>ccsale</ssl_transaction_type>
  <ssl_merchant_id>YOUR_MERCHANT_ID</ssl_merchant_id>
  <ssl_user_id>YOUR_USER_ID</ssl_user_id>
  <ssl_pin>YOUR_PIN</ssl_pin>
  <ssl_amount>10.00</ssl_amount>
  <ssl_card_number>4000000000000002</ssl_card_number>
  <ssl_exp_date>1230</ssl_exp_date>
  <ssl_cvv2cvc2>123</ssl_cvv2cvc2>
</txn>'
```

**Response:** `<ssl_result>0</ssl_result> ... <ssl_result_message>APPROVAL</ssl_result_message>`

#### Affected code

`crates/integrations/connector-integration/src/connectors/elavon/transformers.rs`

```rust
// CardPaymentRequest struct — line ~109
pub ssl_get_token: Option<String>,
pub ssl_transaction_currency: Currency,   // ← always serialized, breaks standard terminals
pub ssl_avs_address: Option<Secret<String>>,
```

#### Proposed Fix

`ssl_transaction_currency` must **not** be sent by default. It should only be included when the merchant's terminal has MCC/DCC enabled.

The cleanest approach is to gate it behind a connector metadata key. If the caller passes `enable_multi_currency: true` in the payment's `connector_metadata`, the field is included; otherwise it is omitted.

```rust
// In CardPaymentRequest
#[serde(skip_serializing_if = "Option::is_none")]
pub ssl_transaction_currency: Option<Currency>,
```

```rust
// In TryFrom construction
let ssl_transaction_currency = request_data
    .connector_metadata
    .as_ref()
    .and_then(|m| m.get("enable_multi_currency"))
    .and_then(|v| v.as_bool())
    .unwrap_or(false)
    .then_some(request_data.currency);
```

Default behaviour: field is not sent. Opt-in: pass `"connector_metadata": {"enable_multi_currency": true}` in the request.

---

#### Description

When Elavon returns an error response (e.g. the `5087` above), the XML contains camelCase field names:

```xml
<txn>
  <errorCode>5087</errorCode>
  <errorName>Transaction currency not allowed for this terminal</errorName>
  <errorMessage>Transaction currency is not allowed for this terminal...</errorMessage>
</txn>
```

The `preprocess_xml_response_bytes` utility converts this XML to flat JSON:

```json
{
  "errorCode": "5087",
  "errorName": "Transaction currency not allowed for this terminal",
  "errorMessage": "Transaction currency is not allowed for this terminal..."
}
```

The inner `XmlIshResponse` struct used inside the custom `Deserialize` implementations for `ElavonPaymentsResponse`, `ElavonCaptureResponse`, and `ElavonRefundResponse` declares the error fields in **snake_case without any rename**:

```rust
#[serde(default)]
error_code: Option<String>,     // looks for key "error_code"  → None (key is "errorCode")
#[serde(default)]
error_message: Option<String>,  // looks for key "error_message" → None (key is "errorMessage")
#[serde(default)]
error_name: Option<String>,     // looks for key "error_name"  → None (key is "errorName")
```

All three fields deserialize as `None`. The deserializer logic then evaluates:

```rust
if flat_res.ssl_result.as_deref() == Some("0") { ... }   // false — no ssl_result in error responses
else if flat_res.error_message.is_some() { ... }          // false — None due to rename mismatch
else if flat_res.ssl_result.is_some() { ... }             // false
else {
    // ← always hits this branch for any Elavon error response
    return Err(de::Error::custom(
        "Invalid Response from Elavon - cannot determine success or error state, missing critical fields.",
    ));
}
```

This propagates as `ResponseDeserializationFailed` → HTTP 500 `"Failed to deserialize connector response"` instead of a proper payment failure response.

#### Reproduce

```bash
# Connector service call — returns 500 instead of a structured error
curl -s -X POST 'http://localhost:8011/payments/authorize' \
  -H 'Content-Type: application/json' \
  -H 'x-connector-config: {"config":{"Elavon":{"ssl_merchant_id":"YOUR_ACCOUNT_ID","ssl_user_id":"YOUR_USER_ID","ssl_pin":"YOUR_PIN"}}}' \
  -H 'x-merchant-id: test_merchant' \
  -H 'x-tenant-id: default' \
  -H 'x-request-id: req_001' \
  -d '{
    "amount": {"minor_amount": 1000, "currency": "USD"},
    "payment_method": {
      "payment_method": {
        "card": {
          "card_number": "4000000000000002",
          "card_exp_month": "12",
          "card_exp_year": "2030",
          "card_cvc": "123",
          "card_holder_name": "Test User"
        }
      }
    },
    "capture_method": "AUTOMATIC",
    "address": {"billing_address": {}},
    "auth_type": "NO_THREE_DS",
    "order_details": []
  }'
```

**Expected:** `{"status": "FAILED", "error": {"code": "5087", "message": "Transaction currency not allowed..."}}`

**Actual:** `{"error": {"message": "Failed to deserialize connector response", "code": "500"}}`

> Note: This is triggered by Bug 1. Any other Elavon error response (declined card, invalid CVV, etc.) would also hit this same deserialization failure.

#### Affected code

`crates/integrations/connector-integration/src/connectors/elavon/transformers.rs` — three `XmlIshResponse` structs inside:
- `impl Deserialize for ElavonPaymentsResponse`
- `impl Deserialize for ElavonCaptureResponse`
- `impl Deserialize for ElavonRefundResponse`

Note: the outer `ElavonErrorResponse` struct already has `#[serde(rename_all = "camelCase")]` correctly, but the inner intermediary `XmlIshResponse` structs are missing the renames.

#### Proposed Fix

Add `rename` attributes matching Elavon's camelCase field names to all three `XmlIshResponse` structs:

```rust
// Before
#[serde(default)]
error_code: Option<String>,
#[serde(default)]
error_message: Option<String>,
#[serde(default)]
error_name: Option<String>,

// After
#[serde(default, rename = "errorCode")]
error_code: Option<String>,
#[serde(default, rename = "errorMessage")]
error_message: Option<String>,
#[serde(default, rename = "errorName")]
error_name: Option<String>,
```

---

### Combined Impact

Both bugs together mean **every single Authorize request on a standard Elavon terminal returns a 500 server error** — Bug 1 forces Elavon to return an error response, and Bug 2 ensures that error response cannot be deserialized.

### PR DESCRIPTION
**Pull request by chaitak-gorai**
## Description

Every Authorize request on a standard Elavon terminal returned `HTTP 500 — "Failed to deserialize connector response"`. Two bugs compounded to cause this.

### Bug 1 — `ssl_transaction_currency` sent unconditionally

`CardPaymentRequest` serialized `ssl_transaction_currency` as a required field on every request. According to Elavon's API, this field is only valid for terminals explicitly configured for Multi-Currency Conversion (MCC) or Dynamic Currency Conversion (DCC). Standard single-currency terminals reject any request containing it with error `5087`:

```xml
<txn>
  <errorCode>5087</errorCode>
  <errorName>Transaction currency not allowed for this terminal</errorName>
  <errorMessage>Transaction currency is not allowed for this terminal. Your terminal must be setup with Multi currency</errorMessage>
</txn>
```

For default case, USD is the default currency of the payment.
---

### Bug 2 — Error response deserialization fails (camelCase / snake_case mismatch)

When Elavon returns an error response, the XML-to-JSON preprocessor produces camelCase keys (`errorCode`, `errorMessage`, `errorName`). The inner `XmlIshResponse` structs inside the custom `Deserialize` implementations for `ElavonPaymentsResponse`, `ElavonCaptureResponse`, and `ElavonRefundResponse` declared these fields in snake_case without any `rename` annotation — so all three fields always deserialized as `None`. The deserializer then fell through to:

```rust
return Err(de::Error::custom(
    "Invalid Response from Elavon - cannot determine success or error state, missing critical fields.",
));
```

This propagated as `ResponseDeserializationFailed` → `HTTP 500 "Failed to deserialize connector response"` for **every** Elavon error — declined cards, invalid CVV, wrong credentials, etc.

Bug 1 forced every request to produce an error response; Bug 2 ensured that error response could never be deserialized. Together: every single Authorize on a standard terminal returned 500.

---

### Bug 1 — Gate `ssl_transaction_currency` behind `connector_feature_data`

`ssl_transaction_currency` is now `Option<Currency>` with `skip_serializing_if = "Option::is_none"`. It is only populated when the caller passes `"multi_currency_enabled": true` inside `connector_feature_data`:

```rust
// CardPaymentRequest
#[serde(skip_serializing_if = "Option::is_none")]
pub ssl_transaction_currency: Option<Currency>,

// TryFrom construction
ssl_transaction_currency: request_data
    .connector_feature_data
    .as_ref()
    .and_then(|d| d.peek().get("multi_currency_enabled"))
    .and_then(|v| v.as_bool())
    .unwrap_or(false)
    .then_some(request_data.currency),
```

- **Default** (no `connector_feature_data`): field is omitted — standard terminals work.
- **Opt-in** for MCC/DCC terminals: pass `"connector_feature_data": "{\"multi_currency_enabled\": true}"`.

---

### Bug 2 — Add `rename` attributes to all three `XmlIshResponse` structs

```rust
// Before
#[serde(default)]
error_code: Option<String>,      // looked for "error_code"    → always None
#[serde(default)]
error_message: Option<String>,   // looked for "error_message" → always None
#[serde(default)]
error_name: Option<String>,      // looked for "error_name"    → always None

// After
#[serde(default, rename = "errorCode")]
error_code: Option<String>,
#[serde(default, rename = "errorMessage")]
error_message: Option<String>,
#[serde(default, rename = "errorName")]
error_name: Option<String>,
```

Applied to `ElavonPaymentsResponse`, `ElavonCaptureResponse`, and `ElavonRefundResponse`.

---

### Additional Changes
- [ ] This PR modifies the API contract
- [ ] This PR modifies application configuration/environment variables

### Test 1 — Standard terminal (no `connector_feature_data`): payment succeeds

`ssl_transaction_currency` is absent from the outbound XML — the terminal accepts the request.

```bash
curl -s -X POST "http://localhost:8011/payments/authorize" \
  -H "Content-Type: application/json" \
  -H "x-connector-config: {\"config\":{\"Elavon\":{\"ssl_merchant_id\":\"<MERCHANT_ID>\",\"ssl_user_id\":\"<USER_ID>\",\"ssl_pin\":\"<PIN>\"}}}" \
  -H "x-merchant-id: test_merchant" \
  -H "x-tenant-id: default" \
  -H "x-request-id: req_no_mcc_001" \
  -d '{
    "amount": {"minor_amount": 1000, "currency": "USD"},
    "payment_method": {
      "payment_method": {
        "card": {
          "card_number": "4000000000000002",
          "card_exp_month": "12",
          "card_exp_year": "2030",
          "card_cvc": "123",
          "card_holder_name": "Test User"
        }
      }
    },
    "capture_method": "AUTOMATIC",
    "address": {"billing_address": {}},
    "auth_type": "NO_THREE_DS",
    "order_details": []
  }'
```

```json
{
  "connector_transaction_id": "170426C44-51F1FD13-D74C-4CF3-B8B2-76636C051C4A",
  "status": "CHARGED",
  "status_code": 200,
  "network_transaction_id": "386123"
}
```

---

### Test 2 — `multi_currency_enabled: true` on a standard terminal: structured failure (not 500)

`ssl_transaction_currency=USD` is included in the XML. Elavon rejects with `5087`, which is now correctly deserialized into a structured `FAILURE` response instead of a 500.

```bash
curl -s -X POST "http://localhost:8011/payments/authorize" \
  -H "Content-Type: application/json" \
  -H "x-connector-config: {\"config\":{\"Elavon\":{\"ssl_merchant_id\":\"<MERCHANT_ID>\",\"ssl_user_id\":\"<USER_ID>\",\"ssl_pin\":\"<PIN>\"}}}" \
  -H "x-merchant-id: test_merchant" \
  -H "x-tenant-id: default" \
  -H "x-request-id: req_mcc_001" \
  -d '{
    "amount": {"minor_amount": 1000, "currency": "USD"},
    "payment_method": {
      "payment_method": {
        "card": {
          "card_number": "4000000000000002",
          "card_exp_month": "12",
          "card_exp_year": "2030",
          "card_cvc": "123",
          "card_holder_name": "Test User"
        }
      }
    },
    "capture_method": "AUTOMATIC",
    "address": {"billing_address": {}},
    "auth_type": "NO_THREE_DS",
    "order_details": [],
    "connector_feature_data": "{\"multi_currency_enabled\": true}"
  }'
```

```json
{
  "status": "FAILURE",
  "error": {
    "connector_details": {
      "code": "5087",
      "message": "Transaction currency is not allowed for this terminal.  Your terminal must be setup with Multi currency",
      "reason": "Transaction currency not allowed for this terminal"
    }
  },
  "status_code": 200
}
```
Expected error as MCC is not enabled in this test account.

### CODE REVIEW

**Review by Shubhodip900 — APPROVED** [review]

**Review by gopikrishna000 — APPROVED** [review]

File: crates/integrations/connector-integration/src/connectors/elavon/transformers.rs [hunk 1]
```diff
@@ -473,11 +480,11 @@ impl<'de> Deserialize<'de> for ElavonPaymentsResponse {
         #[derive(Deserialize, Debug)]
         #[serde(rename = "txn")]
         struct XmlIshResponse {
-            #[serde(default)]
+            #[serde(default, rename = "errorCode")]
```
Comment (swetasharma03) [inline crates/integrations/connector-integration/src/connectors/elavon/transformers.rs:483]: Can we use `#[serde(rename_all = "camelCase")]` at the struct level instead of renaming each field individually?

File: crates/integrations/connector-integration/src/connectors/elavon/transformers.rs [hunk 2]
```diff
@@ -559,11 +566,11 @@ impl<'de> Deserialize<'de> for ElavonCaptureResponse {
...
```
Comment (swetasharma03) [inline crates/integrations/connector-integration/src/connectors/elavon/transformers.rs:569]: +1

File: crates/integrations/connector-integration/src/connectors/elavon/transformers.rs [hunk 3]
```diff
@@ -645,11 +652,11 @@ impl<'de> Deserialize<'de> for ElavonRefundResponse {
...
```
Comment (swetasharma03) [inline crates/integrations/connector-integration/src/connectors/elavon/transformers.rs:655]: +1

File: crates/integrations/connector-integration/src/connectors/elavon/transformers.rs (hunk 1 above)
Comment (chaitak-gorai) [reply crates/integrations/connector-integration/src/connectors/elavon/transformers.rs:483]: we cant rename all fieds to camelCase only the error fields need to be renamed

**Review by swetasharma03 — APPROVED** [review]

File: crates/integrations/connector-integration/src/connectors/elavon/transformers.rs [hunk 4]
```diff
@@ -473,11 +480,11 @@ impl<'de> Deserialize<'de> for ElavonPaymentsResponse {
...
             error_code: Option<String>,
-            #[serde(default)]
+            #[serde(default, rename = "errorMessage")]
             error_message: Option<String>,
-            #[serde(default)]
+            #[serde(default, rename = "errorName")]
```
Comment (deepanshu-iiitu) [inline crates/integrations/connector-integration/src/connectors/elavon/transformers.rs:487]: Use #[serde(rename_all = "camelCase")] for such structs

**Review by deepanshu-iiitu — CHANGES_REQUESTED** [review]

File: crates/integrations/connector-integration/src/connectors/elavon/transformers.rs (hunk 4 above)
Comment (chaitak-gorai) [reply crates/integrations/connector-integration/src/connectors/elavon/transformers.rs:487]: resolved same comment above, please check.

**Review by deepanshu-iiitu — APPROVED** [review]

**Review by Aishwariyaa-Anand — APPROVED** [review]
